# Generated by Django 4.2.6 on 2023-10-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockADS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cod',
            field=models.IntegerField(unique=True),
        ),
    ]
